# Generated by Django 4.2.7 on 2023-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answerlike_questionlike_remove_answer_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='avatar/%Y/%M/%D'),
        ),
    ]
