# Generated by Django 5.0 on 2024-11-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answerlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('profile', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('profile', 'question')},
        ),
    ]
